<!-- AdminMenu -->
<table border="0" cellpadding="0" cellspacing="0" style="background-color:#DCDCDC; width:100%;">
 <tr>
  <td style="vertical-align:top; width:200px;">
   <table class="tableStd" style="width:100%;">
    <tr><th class="cellTitle"><span class="fontTitle">{$smarty.config.langNavigation}</span></th></tr>
    <tr><td class="cellNav{if $action == 'AdminIndex'}Active{/if}" onclick="window.location.href='{$smarty.const.INDEXFILE}?faction=adminpanel{$smarty.const.SID_AMPER}';"><a class="fontNav" href="{$smarty.const.INDEXFILE}?faction=adminpanel{$smarty.const.SID_AMPER}">{Language::getInstance()->getString('overview', 'Help')}</a></td></tr>
    <tr><td class="cellNav{if $action == 'AdminForum'}Active{/if}" onclick="window.location.href='{$smarty.const.INDEXFILE}?faction=ad_forum{$smarty.const.SID_AMPER}';"><a class="fontNav" href="{$smarty.const.INDEXFILE}?faction=ad_forum{$smarty.const.SID_AMPER}">{Language::getInstance()->getString('forums_categories')}</a></td></tr>
    <tr><td class="cellNav{if $action == 'AdminUser'}Active{/if}" onclick="window.location.href='{$smarty.const.INDEXFILE}?faction=ad_user{$smarty.const.SID_AMPER}';"><a class="fontNav" href="{$smarty.const.INDEXFILE}?faction=ad_user{$smarty.const.SID_AMPER}">{Language::getInstance()->getString('members')}</a></td></tr>
    <tr><td class="cellNav{if $action == 'AdminGroup'}Active{/if}" onclick="window.location.href='{$smarty.const.INDEXFILE}?faction=ad_groups{$smarty.const.SID_AMPER}';"><a class="fontNav" href="{$smarty.const.INDEXFILE}?faction=ad_groups{$smarty.const.SID_AMPER}">{Language::getInstance()->getString('groups')}</a></td></tr>
    <tr><td class="cellNav{if $action == 'AdminRank'}Active{/if}" onclick="window.location.href='{$smarty.const.INDEXFILE}?faction=ad_rank{$smarty.const.SID_AMPER}';"><a class="fontNav" href="{$smarty.const.INDEXFILE}?faction=ad_rank{$smarty.const.SID_AMPER}">{Language::getInstance()->getString('user_ranks')}</a></td></tr>
    <tr><td class="cellNav{if $action == 'AdminCensor'}Active{/if}" onclick="window.location.href='{$smarty.const.INDEXFILE}?faction=ad_censor{$smarty.const.SID_AMPER}';"><a class="fontNav" href="{$smarty.const.INDEXFILE}?faction=ad_censor{$smarty.const.SID_AMPER}">{Language::getInstance()->getString('censorships')}</a></td></tr>
    <tr><td class="cellNav{if $action == 'AdminIP'}Active{/if}" onclick="window.location.href='{$smarty.const.INDEXFILE}?faction=ad_ip{$smarty.const.SID_AMPER}';"><a class="fontNav" href="{$smarty.const.INDEXFILE}?faction=ad_ip{$smarty.const.SID_AMPER}">{Language::getInstance()->getString('ip_blocks')}</a></td></tr>
    <tr><td class="cellNav{if $action == 'AdminCalendar'}Active{/if}" onclick="window.location.href='{$smarty.const.INDEXFILE}?faction=adminCalendar{$smarty.const.SID_AMPER}';"><a class="fontNav" href="{$smarty.const.INDEXFILE}?faction=adminCalendar{$smarty.const.SID_AMPER}">{Language::getInstance()->getString('calendar')}</a></td></tr>
    <tr><td class="cellNav{if $action == 'AdminMailBlock'}Active{/if}" onclick="window.location.href='{$smarty.const.INDEXFILE}?faction=adminMailBlock{$smarty.const.SID_AMPER}';"><a class="fontNav" href="{$smarty.const.INDEXFILE}?faction=adminMailBlock{$smarty.const.SID_AMPER}">{Language::getInstance()->getString('mail_blocks')}</a></td></tr>
    <tr><td class="cellNav{if $action == 'AdminSmiley'}Active{/if}" onclick="window.location.href='{$smarty.const.INDEXFILE}?faction=ad_smilies{$smarty.const.SID_AMPER}';"><a class="fontNav" href="{$smarty.const.INDEXFILE}?faction=ad_smilies{$smarty.const.SID_AMPER}">{Language::getInstance()->getString('smilies')}</a></td></tr>
    <tr><td class="cellNav{if $action == 'AdminConfig'}Active{/if}" onclick="window.location.href='{$smarty.const.INDEXFILE}?faction=ad_settings{$smarty.const.SID_AMPER}';"><a class="fontNav" href="{$smarty.const.INDEXFILE}?faction=ad_settings{$smarty.const.SID_AMPER}">{Language::getInstance()->getString('board_settings')}</a></td></tr>
    <tr><td class="cellNav{if $action == 'AdminTemplate'}Active{/if}" onclick="window.location.href='{$smarty.const.INDEXFILE}?faction=adminTemplate{$smarty.const.SID_AMPER}';"><a class="fontNav" href="{$smarty.const.INDEXFILE}?faction=adminTemplate{$smarty.const.SID_AMPER}">{Language::getInstance()->getString('templates')}</a></td></tr>
    <tr><td class="cellNav{if $action == 'AdminLogfile'}Active{/if}" onclick="window.location.href='{$smarty.const.INDEXFILE}?faction=adminLogfile{$smarty.const.SID_AMPER}';"><a class="fontNav" href="{$smarty.const.INDEXFILE}?faction=adminLogfile{$smarty.const.SID_AMPER}">{Language::getInstance()->getString('logfiles')}</a></td></tr>
    <tr><td class="cellNav{if $action == 'AdminNews'}Active{/if}" onclick="window.location.href='{$smarty.const.INDEXFILE}?faction=ad_news{$smarty.const.SID_AMPER}';"><a class="fontNav" href="{$smarty.const.INDEXFILE}?faction=ad_news{$smarty.const.SID_AMPER}">{Language::getInstance()->getString('forum_news')}</a></td></tr>
    <tr><td class="cellNav{if $action == 'AdminNewsletter'}Active{/if}" onclick="window.location.href='{$smarty.const.INDEXFILE}?faction=ad_newsletter{$smarty.const.SID_AMPER}';"><a class="fontNav" href="{$smarty.const.INDEXFILE}?faction=ad_newsletter{$smarty.const.SID_AMPER}">{Language::getInstance()->getString('newsletter')}</a></td></tr>
    <tr><td class="cellNav{if $action == 'AdminMailList'}Active{/if}" onclick="window.location.href='{$smarty.const.INDEXFILE}?faction=ad_emailist{$smarty.const.SID_AMPER}';"><a class="fontNav" href="{$smarty.const.INDEXFILE}?faction=ad_emailist{$smarty.const.SID_AMPER}">{Language::getInstance()->getString('email_list')}</a></td></tr>
    <tr><td class="cellNav{if $action == 'AdminDeleteOld'}Active{/if}" onclick="window.location.href='{$smarty.const.INDEXFILE}?faction=ad_killposts{$smarty.const.SID_AMPER}';"><a class="fontNav" href="{$smarty.const.INDEXFILE}?faction=ad_killposts{$smarty.const.SID_AMPER}">{Language::getInstance()->getString('delete_old_topics')}</a></td></tr>
    <tr><td class="cellNav{if $action == 'AdminPlugIns'}Active{/if}" onclick="window.location.href='{$smarty.const.INDEXFILE}?faction=adminPlugIns{$smarty.const.SID_AMPER}';"><a class="fontNav" href="{$smarty.const.INDEXFILE}?faction=adminPlugIns{$smarty.const.SID_AMPER}">{Language::getInstance()->getString('plug_ins')}</a></td></tr>
    <tr><td class="cellNavNone"><hr class="lineNav" /></td></tr>
   </table>
  </td>
  <td style="width:10px;">&nbsp;</td>
  <td style="vertical-align:top;">
